In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [4]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [5]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
array_of_ones = np.ones((3,4), dtype=np.int16)
array_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [8]:
array_of_empty = np.empty((2,3))
array_of_empty

array([[9.074887e-317, 0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000]])

In [10]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
array_of_floats = np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [14]:
array_2d = np.array([(2,4,6), (3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [15]:
array_2d.shape

(2, 3)

In [16]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [19]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])